# Generated by Django 4.1.7 on 2023-11-29 09:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homestay', '0002_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='GuestFullName',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homestay.userdetails'),
        ),
    ]
