# Generated by Django 4.1.7 on 2023-11-30 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homestay', '0004_homestay'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Homestay',
        ),
    ]
