# Generated by Django 4.1.7 on 2023-12-10 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homestay', '0005_delete_homestay'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='Amount',
        ),
        migrations.AddField(
            model_name='payment',
            name='paymentmethod',
            field=models.CharField(default='default_value_here', max_length=100),
        ),
        migrations.AlterField(
            model_name='payment',
            name='GuestFullName',
            field=models.CharField(max_length=100),
        ),
        migrations.DeleteModel(
            name='userdetails',
        ),
    ]
