# Generated by Django 4.1.7 on 2023-12-10 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homestay', '0006_remove_payment_amount_payment_paymentmethod_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='paymentmethod',
            field=models.CharField(choices=[('khalti', 'Khalti'), ('arrival', 'Pay on Arrival')], default='khalti', max_length=100),
        ),
    ]
