# Generated by Django 4.1.7 on 2023-12-18 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('GuestFullName', models.CharField(max_length=100)),
                ('Email', models.CharField(max_length=100)),
                ('PhoneNumber', models.CharField(max_length=10)),
                ('paymentmethod', models.CharField(choices=[('khalti', 'Khalti'), ('arrival', 'Pay on Arrival')], default='khalti', max_length=100)),
            ],
        ),
    ]
