# Generated by Django 5.0 on 2024-02-29 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_booking_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='amount',
            field=models.IntegerField(),
        ),
    ]
