# Generated by Django 4.1.7 on 2023-12-18 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='paymentmethod',
            field=models.CharField(choices=[('khalti', 'Khalti'), ('arrival', 'Pay on Arrival')], max_length=100),
        ),
    ]
