# Generated by Django 4.1.7 on 2023-12-25 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_alter_payment_paymentmethod'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Payment',
        ),
        migrations.AddField(
            model_name='booking',
            name='paymentmethod',
            field=models.CharField(default='khalti', max_length=255),
        ),
    ]
