# Generated by Django 4.1.7 on 2023-12-25 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_delete_payment_booking_paymentmethod'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='paymentmethod',
        ),
        migrations.AddField(
            model_name='booking',
            name='paymentMethod',
            field=models.CharField(choices=[('khalti', 'Khalti'), ('arrival', 'Pay on Arrival')], default='', max_length=255),
        ),
    ]
