# Generated by Django 4.2.1 on 2023-12-10 22:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Homestay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('homestay_name', models.CharField(max_length=255)),
                ('address', models.TextField()),
                ('location', models.CharField(max_length=255)),
                ('thumbnail_picture', models.ImageField(upload_to='homestay_thumbnails/')),
                ('citizenship_photo', models.ImageField(upload_to='citizenship_photos/')),
                ('email', models.EmailField(max_length=254)),
                ('mobile_number', models.CharField(max_length=20)),
                ('ownership_document_photo', models.ImageField(upload_to='ownership_document_photos/')),
                ('features', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved')], default='pending', max_length=10)),
                ('price', models.CharField(default=2500, max_length=25)),
                ('likes', models.ManyToManyField(blank=True, related_name='liked_homestays', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
